name: Add pull request comment on push

on:
  push
  
jobs:
  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Event is ${{ github.event }}"
      - name: Add comment
        uses: satackey/action-js-inline@v0.0.2
        with:
          script: |
            console.log('Hello world');
